#Ege bölgesi için kira tahmin uygulaması

In [1]:
import numpy as np
import pandas as pd

In [2]:
pip install numpy

Requirement already satisfied: numpy in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\fatmanur\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\fatmanur\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import os
import numpy as np
import pandas as pd

In [5]:
pip install pandas

Requirement already satisfied: pandas in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\fatmanur\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\fatmanur\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\fatmanur\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import os
import numpy as np
import pandas as pd

In [7]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [8]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names: if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
      Column(s) to use as row label(s), denoted either by column labels or column
      indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
      will be formed for the row labels.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g., when you have a malformed file with delimiters at
      the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion.

        .. versionadded:: 1.5.0

            Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
            the default determines the ``dtype`` of the columns which are not explicitly
            listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The 'pyarrow' engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
        per-column ``NA`` values.  By default the following values are interpreted as
        ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
        "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
        "n/a", "nan", "null ".

    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of ``NA`` values placed in non-numeric columns.

        .. deprecated:: 2.2.0
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
          ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
        * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
          as a single date column. Values are joined with a space before parsing.
        * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
          result 'foo'. Values are joined with a space before parsing.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
        format of the ``datetime`` strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.

        .. deprecated:: 2.0.0
            A strict version of this argument is now the default, passing it has no effect.

    keep_date_col : bool, default False
        If ``True`` and ``parse_dates`` specifies combining multiple columns then
        keep the original columns.
    date_parser : Callable, optional
        Function to use for converting a sequence of string columns to an array of
        ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. pandas will try to call ``date_parser`` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by ``parse_dates`` into a single array
        and pass that; and 3) call ``date_parser`` once for each row using one or
        more strings (corresponding to the columns defined by ``parse_dates``) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`~pandas.to_datetime` as-needed.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates when used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
            time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
            and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
        characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
       When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

        .. versionadded:: 1.4.0


In [9]:
df=pd.read_csv('hepsiEmlak/01.csv')

In [10]:
print(df)

                                          img-link href  photo-count  \
0     https://www.hepsiemlak.com/izmir-konak-kilic-r...           17
1     https://www.hepsiemlak.com/izmir-konak-akin-si...           35
2     https://www.hepsiemlak.com/izmir-buca-adatepe-...            5
3     https://www.hepsiemlak.com/izmir-buca-yaylacik...            7
4     https://www.hepsiemlak.com/izmir-karsiyaka-bah...           25
...                                                 ...          ...
1411  https://www.hepsiemlak.com/izmir-cesme-yali-ki...           29
1412  https://www.hepsiemlak.com/izmir-buca-yildiz-k...            4
1413  https://www.hepsiemlak.com/izmir-bayrakli-adal...           22
1414  https://www.hepsiemlak.com/izmir-buca-yaylacik...           15
1415  https://www.hepsiemlak.com/izmir-karsiyaka-sem...           35

     list-view-price list-view-date               left  \
0             12.000     15-04-2024      Kiralık Daire
1             16.000     09-04-2024      Kiralık Daire
2                200     13-04-2024      Kiralık Daire
3                200     13-04-2024      Kiralık Daire
4             18.000     15-04-2024      Kiralık Daire
...              ...            ...                ...
1411         550.000     29-03-2024      Kiralık Villa
1412           9.000     27-03-2024      Kiralık Daire
1413          35.000     05-03-2024  Kiralık Residence
1414          12.000     06-04-2024      Kiralık Daire
1415          15.000     26-03-2024      Kiralık Daire

                               celly celly 2  \
0     1 +\n                        1   55 m²
1     3 +\n                        1  150 m²
2     2 +\n                        1   55 m²
3     2 +\n                        1   60 m²
4     3 +\n                        1  160 m²
...                              ...     ...
1411  3 +\n                        1  250 m²
1412  1 +\n                        1   45 m²
1413  2 +\n                        1   93 m²
1414  2 +\n                        1   90 m²
1415  1 +\n                        1   55 m²

                                celly 3          celly 4  \
0     25\n                      Yaşında     Yüksek Giriş
1     35\n                      Yaşında           3. Kat
2      2\n                      Yaşında          Ara Kat
3      2\n                      Yaşında           3. Kat
4     27\n                      Yaşında           3. Kat
...                                 ...              ...
1411   1\n                      Yaşında       Bahçe Katı
1412   2\n                      Yaşında  Bodrum ve Zemin
1413   5\n                      Yaşında          14. Kat
1414  16\n                      Yaşında       Giriş Katı
1415   4\n                      Yaşında     Yüksek Giriş

                     list-view-location  \
0                                Konak,
1                                Konak,
2                                 Buca,
3                                 Buca,
4     Karşıyaka, Bahçelievler Mahallesi
...                                 ...
1411              Çeşme, Yalı Mahallesi
1412             Buca, Yıldız Mahallesi
1413         Bayraklı, Adalet Mahallesi
1414           Buca, Yaylacık Mahallesi
1415      Karşıyaka, Şemikler Mahallesi

                                           img-wrp href  \
0     https://www.hepsiemlak.com/emlak-ofisi/grup-ga...
1     https://www.hepsiemlak.com/emlak-ofisi/grup-ga...
2     https://www.hepsiemlak.com/emlak-ofisi/eleganc...
3     https://www.hepsiemlak.com/emlak-ofisi/eleganc...
4                                                   NaN
...                                                 ...
1411                                                NaN
1412                                                NaN
1413                                                NaN
1414  https://www.hepsiemlak.com/emlak-ofisi/eg-gayr...
1415                                                NaN

                                      he-lazy-image src  \
0     https://www.hepsiemlak.com/img/loadings/noImag...
1     https://www.hepsiemlak.com/img/loadings/noImag...
2     https://hecdnnw.hemlak.com/mncropresize/91/68/...
3     https://hecdn01.hemlak.com/mncropresize/280/21...
4     https://hecdn01.hemlak.com/mncropresize/182/13...
...                                                 ...
1411  https://hecdn01.hemlak.com/mncropresize/182/13...
1412  https://hecdn01.hemlak.com/mncropresize/182/13...
1413  https://hecdn01.hemlak.com/mncropresize/182/13...
1414  https://hecdn01.hemlak.com/mncropresize/182/13...
1415  https://hecdn01.hemlak.com/mncropresize/182/13...

                                    he-lazy-image src 2  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3     https://hecdnnw.hemlak.com/mncropresize/91/68/...
4                                                   NaN
...                                                 ...
1411                                                NaN
1412                                                NaN
1413                                                NaN
1414  https://hecdnnw.hemlak.com/mncropresize/91/68/...
1415                                                NaN

                                       list-view-header
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4     Karşıyaka Kiralık 2 Balkonlu Naldöken Metro Sa...
...                                                 ...
1411  Çeşme'de Deniz Manzaralı 3+1 Havuzlu Müstakil ...
1412         Buca Yıldız Mahallesinde 1+1 Kiralık Daire
1413  Folkart Towers'ta 2+1 Full Eşyalı Daire By Ayk...
1414                             Kiralık 2+1 Doğalgazlı
1415  Karşıyaka Şemikler Ahmet Piriştina Kültür Merk...

[1416 rows x 14 columns]

In [11]:
df

,img-link href,photo-count,list-view-price,list-view-date,left,celly,celly 2,celly 3,celly 4,list-view-location,img-wrp href,he-lazy-image src,he-lazy-image src 2,list-view-header
0,https://www.hepsiemlak.com/izmir-konak-kilic-r...,17,12.000,15-04-2024,Kiralık Daire,1 +\n 1,55 m²,25\n Yaşında,Yüksek Giriş,"Konak,",https://www.hepsiemlak.com/emlak-ofisi/grup-ga...,https://www.hepsiemlak.com/img/loadings/noImag...,NaN,NaN
1,https://www.hepsiemlak.com/izmir-konak-akin-si...,35,16.000,09-04-2024,Kiralık Daire,3 +\n 1,150 m²,35\n Yaşında,3. Kat,"Konak,",https://www.hepsiemlak.com/emlak-ofisi/grup-ga...,https://www.hepsiemlak.com/img/loadings/noImag...,NaN,NaN
2,https://www.hepsiemlak.com/izmir-buca-adatepe-...,5,200,13-04-2024,Kiralık Daire,2 +\n 1,55 m²,2\n Yaşında,Ara Kat,"Buca,",https://www.hepsiemlak.com/emlak-ofisi/eleganc...,https://hecdnnw.hemlak.com/mncropresize/91/68/...,NaN,NaN
3,https://www.hepsiemlak.com/izmir-buca-yaylacik...,7,200,13-04-2024,Kiralık Daire,2 +\n 1,60 m²,2\n Yaşında,3. Kat,"Buca,",https://www.hepsiemlak.com/emlak-ofisi/eleganc...,https://hecdn01.hemlak.com/mncropresize/280/21...,https://hecdnnw.hemlak.com/mncropresize/91/68/...,NaN
4,https://www.hepsiemlak.com/izmir-karsiyaka-bah...,25,18.000,15-04-2024,Kiralık Daire,3 +\n 1,160 m²,27\n Yaşında,3. Kat,"Karşıyaka, Bahçelievler Mahallesi",NaN,https://hecdn01.hemlak.com/mncropresize/182/13...,NaN,Karşıyaka Kiralık 2 Balkonlu Naldöken Metro Sa...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411,https://www.hepsiemlak.com/izmir-cesme-yali-ki...,29,550.000,29-03-2024,Kiralık Villa,3 +\n 1,250 m²,1\n Yaşında,Bahçe Katı,"Çeşme, Yalı Mahallesi",NaN,https://hecdn01.hemlak.com/mncropresize/182/13...,NaN,Çeşme'de Deniz Manzaralı 3+1 Havuzlu Müstakil ...
1412,https://www.hepsiemlak.com/izmir-buca-yildiz-k...,4,9.000,27-03-2024,Kiralık Daire,1 +\n 1,45 m²,2\n Yaşında,Bodrum ve Zemin,"Buca, Yıldız Mahallesi",NaN,https://hecdn01.hemlak.com/mncropresize/182/13...,NaN,Buca Yıldız Mahallesinde 1+1 Kiralık Daire
1413,https://www.hepsiemlak.com/izmir-bayrakli-adal...,22,35.000,05-03-2024,Kiralık Residence,2 +\n 1,93 m²,5\n Yaşında,14. Kat,"Bayraklı, Adalet Mahallesi",NaN,https://hecdn01.hemlak.com/mncropresize/182/13...,NaN,Folkart Towers'ta 2+1 Full Eşyalı Daire By Ayk...
1414,https://www.hepsiemlak.com/izmir-buca-yaylacik...,15,12.000,06-04-2024,Kiralık Daire,2 +\n 1,90 m²,16\n Yaşında,Giriş Katı,"Buca, Yaylacık Mahallesi",https://www.hepsiemlak.com/emlak-ofisi/eg-gayr...,https://hecdn01.hemlak.com/mncropresize/182/13...,https://hecdnnw.hemlak.com/mncropresize/91/68/...,Kiralık 2+1 Doğalgazlı
1415,https://www.hepsiemlak.com/izmir-karsiyaka-sem...,35,15.000,26-03-2024,Kiralık Daire,1 +\n 1,55 m²,4\n Yaşında,Yüksek Giriş,"Karşıyaka, Şemikler Mahallesi",NaN,https://hecdn01.hemlak.com/mncropresize/182/13...,NaN,Karşıyaka Şemikler Ahmet Piriştina Kültür Merk...

In [12]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'celly',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'left',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1416 entries, 0 to 1415
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   img-link href        1416 non-null   object
 1   photo-count          1416 non-null   int64
 2   list-view-price      1416 non-null   object
 3   list-view-date       1416 non-null   object
 4   left                 1416 non-null   object
 5   celly                1416 non-null   object
 6   celly 2              1416 non-null   object
 7   celly 3              1416 non-null   object
 8   celly 4              1247 non-null   object
 9   list-view-location   1416 non-null   object
 10  img-wrp href         642 non-null    object
 11  he-lazy-image src    1321 non-null   object
 12  he-lazy-image src 2  563 non-null    object
 13  list-view-header     1412 non-null   object
dtypes: int64(1), object(13)
memory usage: 155.0+ KB
None

In [14]:
dir(os)

['DirEntry',
 'EX_OK',
 'F_OK',
 'GenericAlias',
 'Mapping',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_AddedDllDirectory',
 '_Environ',
 '__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_check_methods',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'add_dll_directory',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fdopen',
 'fsdecode',
 'fsencode',
 'fspath',
 'fstat',
 'fsync',
 'ftruncate',
 'get_blocking',
 'get_exec_path',
 'get_handle_inheritable',
 'get_inheritable',
 'get_terminal_size',
 'getcwd',
 'getcwdb',
 'getenv',
 'getlogin',
 'getpid',
 'getppid',
 'isatty',
 'kill',
 'linesep',
 'link',
 'listdir',
 'listdrives',
 'listmounts',
 'listvolumes',
 'lseek',
 'lstat',
 'makedirs',
 'mkdir',
 'name',
 'open',
 'pardir',
 'path',
 'pathsep',
 'pipe',
 'popen',
 'putenv',
 'read',
 'readlink',
 'remove',
 'removedirs',
 'rename',
 'renames',
 'replace',
 'rmdir',
 'scandir',
 'sep',
 'set_blocking',
 'set_handle_inheritable',
 'set_inheritable',
 'spawnl',
 'spawnle',
 'spawnv',
 'spawnve',
 'st',
 'startfile',
 'stat',
 'stat_result',
 'statvfs_result',
 'strerror',
 'supports_bytes_environ',
 'supports_dir_fd',
 'supports_effective_ids',
 'supports_fd',
 'supports_follow_symlinks',
 'symlink',
 'sys',
 'system',
 'terminal_size',
 'times',
 'times_result',
 'truncate',
 'umask',
 'uname_result',
 'unlink',
 'unsetenv',
 'urandom',
 'utime',
 'waitpid',
 'waitstatus_to_exitcode',
 'walk',
 'write']

In [15]:
help(os.listdir)

Help on built-in function listdir in module nt:

listdir(path=None)
    Return a list containing the names of the files in the directory.

    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.

    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.

In [16]:
def drop_columns(df, cols):
    """
    This function removes the columns from a dataFrame
    """
    for col in cols :
        try:
            df.drop([col], axis=1, inplace=True)
        except Exception as e:
            print(f"bir hata oluştu:{e}")

In [17]:
files = os.listdir('hepsiEmlak')
df= pd.concat([pd.read_csv(f"hepsiEmlak/{file}") for file in files] , ignore_index=True)

   # df= pd.read_csv(f"hepsiEmlak/{file}") #f-string formu
    #df = pd.read_csv('hepsiEmlak/' + file) üstekiyle aynı
    #Bu kod, "hepsiEmlak/" dizini ile file değişkeninin değerini birleştirerek sonuç olarak "hepsiEmlak/veri.csv" dizesini oluşturur ve bu dizeyi pd.read_csv() işlevine geçirir

In [18]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   img-link href        8136 non-null   object
 1   photo-count          8130 non-null   float64
 2   list-view-price      8136 non-null   object
 3   list-view-date       8136 non-null   object
 4   left                 8114 non-null   object
 5   celly                8136 non-null   object
 6   celly 2              8136 non-null   object
 7   celly 3              8136 non-null   object
 8   celly 4              6858 non-null   object
 9   list-view-location   8136 non-null   object
 10  img-wrp href         4555 non-null   object
 11  he-lazy-image src    7649 non-null   object
 12  he-lazy-image src 2  4067 non-null   object
 13  list-view-header     8129 non-null   object
 14  branded__text        134 non-null    object
 15  branded__text 2      134 non-null    object
 16  img-wrp href 2       133 non-null    object
 17  he-lazy-image src 3  116 non-null    object
dtypes: float64(1), object(17)
memory usage: 1.1+ MB
None

In [19]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'branded__text',
 'celly',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'left',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [20]:
print(df.head()) #ilk 5 satırı döndürür

                                       img-link href  photo-count  \
0  https://www.hepsiemlak.com/izmir-konak-kilic-r...         17.0
1  https://www.hepsiemlak.com/izmir-konak-akin-si...         35.0
2  https://www.hepsiemlak.com/izmir-buca-adatepe-...          5.0
3  https://www.hepsiemlak.com/izmir-buca-yaylacik...          7.0
4  https://www.hepsiemlak.com/izmir-karsiyaka-bah...         25.0

  list-view-price list-view-date           left  \
0          12.000     15-04-2024  Kiralık Daire
1          16.000     09-04-2024  Kiralık Daire
2             200     13-04-2024  Kiralık Daire
3             200     13-04-2024  Kiralık Daire
4          18.000     15-04-2024  Kiralık Daire

                            celly celly 2                            celly 3  \
0  1 +\n                        1   55 m²  25\n                      Yaşında
1  3 +\n                        1  150 m²  35\n                      Yaşında
2  2 +\n                        1   55 m²   2\n                      Yaşında
3  2 +\n                        1   60 m²   2\n                      Yaşında
4  3 +\n                        1  160 m²  27\n                      Yaşında

        celly 4                 list-view-location  \
0  Yüksek Giriş                             Konak,
1        3. Kat                             Konak,
2       Ara Kat                              Buca,
3        3. Kat                              Buca,
4        3. Kat  Karşıyaka, Bahçelievler Mahallesi

                                        img-wrp href  \
0  https://www.hepsiemlak.com/emlak-ofisi/grup-ga...
1  https://www.hepsiemlak.com/emlak-ofisi/grup-ga...
2  https://www.hepsiemlak.com/emlak-ofisi/eleganc...
3  https://www.hepsiemlak.com/emlak-ofisi/eleganc...
4                                                NaN

                                   he-lazy-image src  \
0  https://www.hepsiemlak.com/img/loadings/noImag...
1  https://www.hepsiemlak.com/img/loadings/noImag...
2  https://hecdnnw.hemlak.com/mncropresize/91/68/...
3  https://hecdn01.hemlak.com/mncropresize/280/21...
4  https://hecdn01.hemlak.com/mncropresize/182/13...

                                 he-lazy-image src 2  \
0                                                NaN
1                                                NaN
2                                                NaN
3  https://hecdnnw.hemlak.com/mncropresize/91/68/...
4                                                NaN

                                    list-view-header branded__text  \
0                                                NaN           NaN
1                                                NaN           NaN
2                                                NaN           NaN
3                                                NaN           NaN
4  Karşıyaka Kiralık 2 Balkonlu Naldöken Metro Sa...           NaN

  branded__text 2 img-wrp href 2 he-lazy-image src 3
0             NaN            NaN                 NaN
1             NaN            NaN                 NaN
2             NaN            NaN                 NaN
3             NaN            NaN                 NaN
4             NaN            NaN                 NaN

In [21]:
print(df.sample(50))  #rastgele 50 veriyi yazzdırır.

                                          img-link href  photo-count  \
5339  https://www.hepsiemlak.com/denizli-merkezefend...         14.0
4883  https://www.hepsiemlak.com/denizli-pamukkale-i...         10.0
1248  https://www.hepsiemlak.com/izmir-balcova-onur-...         18.0
1521  https://www.hepsiemlak.com/izmir-bayrakli-post...         21.0
3379  https://www.hepsiemlak.com/izmir-karsiyaka-yal...         23.0
6432  https://www.hepsiemlak.com/mugla-bodrum-bitez-...         17.0
8094  https://www.hepsiemlak.com/mugla-bodrum-kumbah...          6.0
842   https://www.hepsiemlak.com/izmir-gaziemir-irma...         13.0
6034  https://www.hepsiemlak.com/mugla-datca-datca-k...         23.0
4499  https://www.hepsiemlak.com/aydin-kusadasi-davu...          1.0
4468  https://www.hepsiemlak.com/aydin-didim-hisar-k...         28.0
2614  https://www.hepsiemlak.com/izmir-odemis-zafer-...         12.0
2814  https://www.hepsiemlak.com/izmir-balcova-egiti...         17.0
254   https://www.hepsiemlak.com/izmir-bayrakli-osma...         27.0
6695  https://www.hepsiemlak.com/mugla-fethiye-catal...         12.0
4741  https://www.hepsiemlak.com/aydin-kusadasi-ikic...          9.0
422   https://www.hepsiemlak.com/izmir-gaziemir-atif...         26.0
1856  https://www.hepsiemlak.com/izmir-gaziemir-irma...         35.0
4623  https://www.hepsiemlak.com/aydin-kusadasi-davu...         17.0
4523  https://www.hepsiemlak.com/aydin-efeler-adnan-...         25.0
1144  https://www.hepsiemlak.com/izmir-buca-firat-ki...         12.0
7152  https://www.hepsiemlak.com/mugla-mentese-orhan...         19.0
5459  https://www.hepsiemlak.com/denizli-merkezefend...          8.0
2225  https://www.hepsiemlak.com/izmir-karsiyaka-ded...         38.0
2091  https://www.hepsiemlak.com/izmir-seferihisar-b...         27.0
499   https://www.hepsiemlak.com/izmir-konak-alsanca...         39.0
773   https://www.hepsiemlak.com/izmir-cesme-yali-ki...         14.0
4983  https://www.hepsiemlak.com/denizli-cameli-yeni...         14.0
355   https://www.hepsiemlak.com/izmir-gaziemir-gazi...         17.0
4111  https://www.hepsiemlak.com/aydin-kusadasi-davu...         30.0
3067  https://www.hepsiemlak.com/izmir-konak-murat-r...         17.0
2231  https://www.hepsiemlak.com/izmir-seferihisar-c...         31.0
2608  https://www.hepsiemlak.com/izmir-karsiyaka-bos...         22.0
5128  https://www.hepsiemlak.com/denizli-pamukkale-g...         14.0
1964  https://www.hepsiemlak.com/izmir-cesme-musalla...         12.0
5003  https://www.hepsiemlak.com/denizli-pamukkale-a...         18.0
7702  https://www.hepsiemlak.com/mugla-ula-akyaka-ki...         11.0
1635  https://www.hepsiemlak.com/izmir-konak-kultur-...         29.0
1188  https://www.hepsiemlak.com/izmir-narlidere-nar...         23.0
119   https://www.hepsiemlak.com/izmir-cesme-alacati...         47.0
7921  https://www.hepsiemlak.com/mugla-mentese-musli...         12.0
6025  https://www.hepsiemlak.com/mugla-milas-gulluk-...         37.0
3538  https://www.hepsiemlak.com/izmir-cesme-yali-ki...         30.0
4157  https://www.hepsiemlak.com/aydin-kusadasi-davu...          7.0
2780  https://www.hepsiemlak.com/izmir-guzelbahce-si...         10.0
6151  https://www.hepsiemlak.com/mugla-fethiye-tuzla...         16.0
7143  https://www.hepsiemlak.com/mugla-bodrum-yeniko...         18.0
5735  https://www.hepsiemlak.com/mugla-bodrum-geris-...         28.0
4220  https://www.hepsiemlak.com/aydin-kusadasi-ikic...         24.0
4426  https://www.hepsiemlak.com/aydin-nazilli-sumer...         10.0

     list-view-price list-view-date                 left  \
5339          13.000     08-03-2024        Kiralık Daire
4883           8.500     15-04-2024        Kiralık Daire
1248          18.000     25-03-2024        Kiralık Daire
1521          27.500     21-03-2024        Kiralık Daire
3379          25.000     19-03-2024        Kiralık Daire
6432          30.000     06-04-2024        Kiralık Daire
8094          25.000     22-03-2024        Kiralık Daire
842           15.000     07-04-2024        Kiralık Daire
6034          40.000     18-03-2024        Kiralık Villa
4499          12.000     12-04-2024        Kiralık Daire
4468          15.000     28-03-2024        Kiralık Daire
2614          13.000     16-04-2024        Kiralık Daire
2814          14.000     11-03-2024        Kiralık Daire
254           12.500     13-04-2024        Kiralık Daire
6695          12.000     09-04-2024        Kiralık Daire
4741          12.000     15-03-2024        Kiralık Daire
422           22.000     15-04-2024        Kiralık Daire
1856          20.000     30-03-2024        Kiralık Daire
4623          15.000     02-02-2024        Kiralık Villa
4523          16.000     08-03-2024        Kiralık Daire
1144          20.000     01-04-2024        Kiralık Daire
7152          18.000     03-02-2024        Kiralık Daire
5459          10.000     15-04-2024        Kiralık Daire
2225          25.000     15-02-2024        Kiralık Daire
2091          14.500     06-04-2024       Kiralık Yazlık
499           25.000     08-04-2024        Kiralık Daire
773          300.000     07-04-2024        Kiralık Villa
4983           8.000     02-04-2024        Kiralık Daire
355           28.000     11-04-2024        Kiralık Daire
4111           1.500     11-04-2024        Kiralık Daire
3067          12.000     06-02-2024        Kiralık Daire
2231          17.500     20-01-2024        Kiralık Daire
2608          18.000     27-02-2024        Kiralık Daire
5128          14.000     31-03-2024        Kiralık Daire
1964         325.000     10-04-2024    Kiralık Residence
5003           8.500     03-04-2024        Kiralık Daire
7702          15.000     08-04-2024        Kiralık Daire
1635          52.500     01-04-2024        Kiralık Daire
1188          19.000     02-04-2024        Kiralık Daire
119          300.000     15-04-2024        Kiralık Villa
7921           7.500     04-03-2024        Kiralık Daire
6025         250.000     08-04-2024        Kiralık Villa
3538         330.000     03-04-2024        Kiralık Villa
4157          13.000     09-04-2024        Kiralık Daire
2780          20.000     27-03-2024        Kiralık Daire
6151          20.000     13-04-2024        Kiralık Daire
7143          20.000     07-02-2024        Kiralık Daire
5735          75.000     15-04-2024  Kiralık Müstakil Ev
4220          15.000     29-03-2024        Kiralık Daire
4426         890.000     12-03-2024        Kiralık Daire

                               celly celly 2  \
5339  3 +\n                        1  145 m²
4883  2 +\n                        1   65 m²
1248  3 +\n                        1  110 m²
1521  3 +\n                        1  160 m²
3379  2 +\n                        1   80 m²
6432  2 +\n                        1   90 m²
8094  1 +\n                        1   75 m²
842   3 +\n                        1  140 m²
6034  2 +\n                        1  140 m²
4499  2 +\n                        1  100 m²
4468  2 +\n                        1   90 m²
2614  3 +\n                        1  150 m²
2814  3 +\n                        1  120 m²
254   3 +\n                        1  125 m²
6695  2 +\n                        1   85 m²
4741  1 +\n                        1   50 m²
422   2 +\n                        1  110 m²
1856  3 +\n                        1  125 m²
4623  3 +\n                        1  150 m²
4523  4 +\n                        1  220 m²
1144  2 +\n                        1  100 m²
7152  3 +\n                        1  150 m²
5459  1 +\n                        1   45 m²
2225  4 +\n                        1  180 m²
2091  1 +\n                        1   75 m²
499   3 +\n                        1  125 m²
773   3 +\n                        1  150 m²
4983  2 +\n                        1   60 m²
355   3 +\n                        1  140 m²
4111  1 +\n                        1   65 m²
3067  3 +\n                        1  120 m²
2231  2 +\n                        1  100 m²
2608  3 +\n                        1  120 m²
5128  2 +\n                        1  110 m²
1964  1 +\n                        1  137 m²
5003  1 +\n                        1   65 m²
7702  1 +\n                        1   60 m²
1635  3 +\n                        1  145 m²
1188  3 +\n                        1  130 m²
119   4 +\n                        1  160 m²
7921                          Stüdyo   35 m²
6025  4 +\n                        2  400 m²
3538  3 +\n                        1  120 m²
4157  1 +\n                        1   70 m²
2780  2 +\n                        1  100 m²
6151  2 +\n                        1  110 m²
7143  2 +\n                        1  130 m²
5735  4 +\n                        1  160 m²
4220  3 +\n                        1  125 m²
4426  1 +\n                        1   57 m²

                                 celly 3       celly 4  \
5339   21\n                      Yaşında        3. Kat
4883   10\n                      Yaşında       Ara Kat
1248   30\n                      Yaşında        1. Kat
1521   12\n                      Yaşında        7. Kat
3379   11\n                      Yaşında        4. Kat
6432   11\n                      Yaşında    Giriş Katı
8094   20\n                      Yaşında    En Üst Kat
842    20\n                      Yaşında        3. Kat
6034    7\n                      Yaşında           NaN
4499    2\n                      Yaşında        3. Kat
4468   10\n                      Yaşında        1. Kat
2614   17\n                      Yaşında        2. Kat
2814   40\n                      Yaşında        2. Kat
254    20\n                      Yaşında        2. Kat
6695    5\n                      Yaşında        2. Kat
4741   30\n                      Yaşında        4. Kat
422     9\n                      Yaşında       Ara Kat
1856   21\n                      Yaşında        3. Kat
4623   15\n                      Yaşında           NaN
4523   11\n                      Yaşında        2. Kat
1144   30\n                      Yaşında       Ara Kat
7152   25\n                      Yaşında        1. Kat
5459                          Sıfır Bina  Yüksek Giriş
2225   11\n                      Yaşında        3. Kat
2091   10\n                      Yaşında    Bahçe Katı
499    35\n                      Yaşında    En Üst Kat
773    12\n                      Yaşında           NaN
4983   10\n                      Yaşında        2. Kat
355    11\n                      Yaşında        4. Kat
4111    2\n                      Yaşında       Ara Kat
3067   30\n                      Yaşında        4. Kat
2231    2\n                      Yaşında        3. Kat
2608  300\n                      Yaşında  Yüksek Giriş
5128    1\n                      Yaşında        3. Kat
1964    4\n                      Yaşında        3. Kat
5003    3\n                      Yaşında        2. Kat
7702   25\n                      Yaşında    En Üst Kat
1635   30\n                      Yaşında       Ara Kat
1188   25\n                      Yaşında        3. Kat
119     9\n                      Yaşında           NaN
7921   15\n                      Yaşında        Bodrum
6025    5\n                      Yaşında           NaN
3538    3\n                      Yaşında           NaN
4157    5\n                      Yaşında       Ara Kat
2780    3\n                      Yaşında        5. Kat
6151   15\n                      Yaşında        3. Kat
7143   10\n                      Yaşında        2. Kat
5735   11\n                      Yaşında           NaN
4220   18\n                      Yaşında    Giriş Katı
4426                          Sıfır Bina        2. Kat

                            list-view-location  \
5339           Merkezefendi, Akkonak Mahallesi
4883          Pamukkale, İncilipınar Mahallesi
1248                   Balçova, Onur Mahallesi
1521            Bayraklı, Postacılar Mahallesi
3379                 Karşıyaka, Yalı Mahallesi
6432                   Bodrum, Bitez Mahallesi
8094                Bodrum, Kumbahçe Mahallesi
842                  Gaziemir, Irmak Mahallesi
6034                    Datça, Datça Mahallesi
4499              Kuşadası, Davutlar Mahallesi
4468                    Didim, Hisar Mahallesi
2614                   Ödemiş, Zafer Mahallesi
2814                 Balçova, Eğitim Mahallesi
254              Bayraklı, Osmangazi Mahallesi
6695              Fethiye, Çatalarık Mahallesi
4741           Kuşadası, İkiçeşmelik Mahallesi
422                Gaziemir, Atıfbey Mahallesi
1856                 Gaziemir, Irmak Mahallesi
4623              Kuşadası, Davutlar Mahallesi
4523          Efeler, Adnan Menderes Mahallesi
1144                     Buca, Fırat Mahallesi
7152               Menteşe, Orhaniye Mahallesi
5459          Merkezefendi, Şemikler Mahallesi
2225             Karşıyaka, Dedebaşı Mahallesi
2091           Seferihisar, Bengiler Mahallesi
499                  Konak, Alsancak Mahallesi
773                      Çeşme, Yalı Mahallesi
4983                    Çameli, Yeni Mahallesi
355                   Gaziemir, Gazi Mahallesi
4111              Kuşadası, Davutlar Mahallesi
3067               Konak, Murat Reis Mahallesi
2231  Seferihisar, Çolak İbrahim Bey Mahallesi
2608             Karşıyaka, Bostanlı Mahallesi
5128             Pamukkale, Gökpınar Mahallesi
1964                  Çeşme, Musalla Mahallesi
5003               Pamukkale, Atalar Mahallesi
7702                     Ula, Akyaka Mahallesi
1635                   Konak, Kültür Mahallesi
1188                Narlıdere, Narlı Mahallesi
119                   Çeşme, Alaçatı Mahallesi
7921            Menteşe, Muslihittin Mahallesi
6025                   Milas, Güllük Mahallesi
3538                     Çeşme, Yalı Mahallesi
4157              Kuşadası, Davutlar Mahallesi
2780             Güzelbahçe, Siteler Mahallesi
6151                  Fethiye, Tuzla Mahallesi
7143                 Bodrum, Yeniköy Mahallesi
5735                   Bodrum, Geriş Mahallesi
4220           Kuşadası, İkiçeşmelik Mahallesi
4426                  Nazilli, Sümer Mahallesi

                                           img-wrp href  \
5339  https://www.hepsiemlak.com/emlak-ofisi/eysu-ka...
4883                                                NaN
1248                                                NaN
1521                                                NaN
3379  https://www.hepsiemlak.com/emlak-ofisi/remax-m...
6432                                                NaN
8094                                                NaN
842   https://www.hepsiemlak.com/emlak-ofisi/gaziemi...
6034  https://www.hepsiemlak.com/emlak-ofisi/coldwel...
4499  https://www.hepsiemlak.com/emlak-ofisi/guzelca...
4468  https://www.hepsiemlak.com/emlak-ofisi/alievim...
2614                                                NaN
2814                                                NaN
254                                                 NaN
6695  https://www.hepsiemlak.com/emlak-ofisi/fethiye...
4741                                                NaN
422                                                 NaN
1856  https://www.hepsiemlak.com/emlak-ofisi/fun-gay...
4623  https://www.hepsiemlak.com/emlak-ofisi/yildiz-...
4523  https://www.hepsiemlak.com/emlak-ofisi/baran-e...
1144                                                NaN
7152                                                NaN
5459  https://www.hepsiemlak.com/emlak-ofisi/prime-t...
2225                                                NaN
2091                                                NaN
499                                                 NaN
773   https://www.hepsiemlak.com/emlak-ofisi/kat-gay...
4983                                                NaN
355                                                 NaN
4111  https://www.hepsiemlak.com/emlak-ofisi/jet-eml...
3067                                                NaN
2231                                                NaN
2608                                                NaN
5128                                                NaN
1964  https://www.hepsiemlak.com/emlak-ofisi/kw-ales...
5003  https://www.hepsiemlak.com/emlak-ofisi/ulaman-...
7702                                                NaN
1635  https://www.hepsiemlak.com/emlak-ofisi/coldwel...
1188  https://www.hepsiemlak.com/emlak-ofisi/a24-sit...
119   https://www.hepsiemlak.com/emlak-ofisi/arda-ga...
7921                                                NaN
6025  https://www.hepsiemlak.com/emlak-ofisi/aj-mima...
3538  https://www.hepsiemlak.com/emlak-ofisi/ozkanla...
4157  https://www.hepsiemlak.com/emlak-ofisi/captain...
2780  https://www.hepsiemlak.com/emlak-ofisi/remax-f...
6151  https://www.hepsiemlak.com/emlak-ofisi/koordin...
7143  https://www.hepsiemlak.com/emlak-ofisi/baser-e...
5735  https://www.hepsiemlak.com/emlak-ofisi/bosel-g...
4220  https://www.hepsiemlak.com/emlak-ofisi/kusadas...
4426                                                NaN

                                      he-lazy-image src  \
5339  https://hecdn01.hemlak.com/mncropresize/182/13...
4883  https://hecdn01.hemlak.com/mncropresize/182/13...
1248                                                NaN
1521  https://hecdn01.hemlak.com/mncropresize/182/13...
3379  https://hecdn01.hemlak.com/mncropresize/182/13...
6432                                                NaN
8094  https://hecdn01.hemlak.com/mncropresize/182/13...
842   https://hecdnnw.hemlak.com/mncropresize/91/68/...
6034  https://hecdn01.hemlak.com/mncropresize/182/13...
4499  https://hecdnnw.hemlak.com/mncropresize/91/68/...
4468  https://hecdn01.hemlak.com/mncropresize/182/13...
2614  https://hecdn01.hemlak.com/mncropresize/182/13...
2814  https://hecdn01.hemlak.com/mncropresize/182/13...
254   https://hecdn01.hemlak.com/mncropresize/182/13...
6695  https://hecdn01.hemlak.com/mncropresize/182/13...
4741  https://hecdn01.hemlak.com/mncropresize/182/13...
422   https://hecdn01.hemlak.com/mncropresize/182/13...
1856  https://hecdn01.hemlak.com/mncropresize/182/13...
4623  https://hecdn01.hemlak.com/mncropresize/182/13...
4523  https://hecdnnw.hemlak.com/mncropresize/91/68/...
1144  https://hecdn01.hemlak.com/mncropresize/182/13...
7152                                                NaN
5459  https://hecdn01.hemlak.com/mncropresize/182/13...
2225  https://hecdn01.hemlak.com/mncropresize/182/13...
2091  https://hecdn01.hemlak.com/mncropresize/182/13...
499   https://hecdn01.hemlak.com/mncropresize/182/13...
773   https://hecdn01.hemlak.com/mncropresize/182/13...
4983                                                NaN
355   https://hecdn01.hemlak.com/mncropresize/182/13...
4111  https://hecdn01.hemlak.com/mncropresize/182/13...
3067  https://hecdn01.hemlak.com/mncropresize/182/13...
2231  https://hecdn01.hemlak.com/mncropresize/182/13...
2608  https://hecdn01.hemlak.com/mncropresize/182/13...
5128  https://hecdn01.hemlak.com/mncropresize/182/13...
1964  https://hecdn01.hemlak.com/mncropresize/182/13...
5003  https://hecdn01.hemlak.com/mncropresize/182/13...
7702  https://hecdn01.hemlak.com/mncropresize/182/13...
1635  https://hecdn01.hemlak.com/mncropresize/182/13...
1188  https://hecdn01.hemlak.com/mncropresize/182/13...
119   https://hecdn01.hemlak.com/mncropresize/182/13...
7921                                                NaN
6025  https://hecdnnw.hemlak.com/mncropresize/68/68/...
3538  https://hecdn01.hemlak.com/mncropresize/182/13...
4157  https://hecdn01.hemlak.com/mncropresize/182/13...
2780  https://hecdn01.hemlak.com/mncropresize/182/13...
6151  https://hecdn01.hemlak.com/mncropresize/182/13...
7143  https://hecdn01.hemlak.com/mncropresize/182/13...
5735  https://hecdn01.hemlak.com/mncropresize/182/13...
4220  https://hecdn01.hemlak.com/mncropresize/182/13...
4426                                                NaN

                                    he-lazy-image src 2  \
5339  https://hecdnnw.hemlak.com/mncropresize/91/68/...
4883                                                NaN
1248                                                NaN
1521                                                NaN

In [22]:
print(df.columns)

Index(['img-link href', 'photo-count', 'list-view-price', 'list-view-date',
       'left', 'celly', 'celly 2', 'celly 3', 'celly 4', 'list-view-location',
       'img-wrp href', 'he-lazy-image src', 'he-lazy-image src 2',
       'list-view-header', 'branded__text', 'branded__text 2',
       'img-wrp href 2', 'he-lazy-image src 3'],
      dtype='object')

In [23]:
cols= ['photo-count', 'list-view-date', 'list-view-location', 'he-lazy-image src', 'left', 'list-view-header', 'branded__text', 'branded__text 2', 'img-wrp href 2', 'he-lazy-image src 3', 'he-lazy-image src 2']
drop_columns(df, cols)

In [24]:
print(df.columns)

Index(['img-link href', 'list-view-price', 'celly', 'celly 2', 'celly 3',
       'celly 4', 'img-wrp href'],
      dtype='object')

In [25]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   img-link href    8136 non-null   object
 1   list-view-price  8136 non-null   object
 2   celly            8136 non-null   object
 3   celly 2          8136 non-null   object
 4   celly 3          8136 non-null   object
 5   celly 4          6858 non-null   object
 6   img-wrp href     4555 non-null   object
dtypes: object(7)
memory usage: 445.1+ KB
None

In [26]:
#img-link href'den il ilçe mahalle çekilcek
#"https:  // www.hepsiemlak.com/ izmir-buca-adatepe-kiralik/ daire/138098-14
print(df['img-link href'].unique())

['https://www.hepsiemlak.com/izmir-konak-kilic-reis-kiralik/daire/130125-62'
 'https://www.hepsiemlak.com/izmir-konak-akin-simav-kiralik/daire/130125-91'
 'https://www.hepsiemlak.com/izmir-buca-adatepe-kiralik/daire/138098-14'
 ...
 'https://www.hepsiemlak.com/mugla-mentese-yenikoy-kiralik/daire/76834-2215'
 'https://www.hepsiemlak.com/mugla-bodrum-turkbuku-kiralik/yazlik/5343-8596'
 'https://www.hepsiemlak.com/mugla-ortaca-cayli-kiralik/daire/82884-1210']

In [27]:
df['location']= df['img-link href'].apply(lambda x: x.split('/')[3])
df['city'] = df['location'].str.split('-').str[0]
df['district'] = df['location'].str.split('-').str[1]
df['neighborhood']= df['location'].str.split('-').str[2:-1]

df['neighborhood']= df ['neighborhood'].apply(lambda x: '_'.join(x))

In [28]:
s="https://www.hepsiemlak.com/izmir-konak-kilic-reis-kiralik/daire/130125-62"

In [29]:
dir(s)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [30]:
#split kullanılarak karaktere göre parçalıcaz

In [31]:
x=s.split('/')[3]

In [32]:
x.split("-")[2:-1] #mahallede kılıç-reis şeklinde gösteriyor bunu düzeltcez

['kilic', 'reis']

In [33]:
"_".join(x.split('-')[2:-1])

'kilic_reis'

In [34]:
drop_columns(df, ['location', 'img-link href'])

In [35]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   celly            8136 non-null   object
 2   celly 2          8136 non-null   object
 3   celly 3          8136 non-null   object
 4   celly 4          6858 non-null   object
 5   img-wrp href     4555 non-null   object
 6   city             8136 non-null   object
 7   district         8136 non-null   object
 8   neighborhood     8136 non-null   object
dtypes: object(9)
memory usage: 572.2+ KB
None

In [36]:
print(df[['city', 'district','neighborhood']] .sample (50))

                city      district    neighborhood
1629           izmir         konak        alsancak
2310           izmir          urla        bademler
5498         denizli  merkezefendi         gultepe
413            izmir         cigli        balatcik
3702          manisa      turgutlu       ergenekon
229            izmir         cesme        germiyan
2091           izmir   seferihisar        bengiler
3260           izmir         cesme           ilica
6810           mugla       fethiye         esenkoy
1872           izmir          buca       akincilar
4407           aydin        efeler           zafer
7379           mugla      koycegiz            yeni
4086           aydin        efeler  adnan_menderes
3549           izmir         cesme        16_eylul
3967  afyonkarahisar        merkez         kanlica
6282           mugla       fethiye           gocek
2990           izmir     narlidere        yenikale
2437           izmir         cesme           ardic
4087           aydin         didim           hisar
3415           izmir         cesme         alacati
5850           mugla           ula       alparslan
5281         denizli     pamukkale     incilipinar
3065           izmir        dikili      cumhuriyet
1043           izmir    guzelbahce            yali
163            izmir         cigli        balatcik
1680           izmir     karsiyaka        dedebasi
6118           mugla        bodrum           bitez
429            izmir       balcova       teleferik
1039           izmir         konak      kilic_reis
8090           mugla        bodrum     guvercinlik
4011  afyonkarahisar        merkez        mecidiye
3583           izmir     karsiyaka        bostanli
1794           izmir         cesme           ilica
3962  afyonkarahisar        merkez      osman_gazi
327            izmir     karsiyaka        bostanli
3751          manisa     yunusemre        muradiye
4908         denizli     pamukkale          atalar
7916           mugla        bodrum       eskicesme
5482         denizli     pamukkale         kinikli
5909           mugla        bodrum       koyunbaba
4270           aydin      kusadasi        davutlar
3916         kutahya        merkez       yunusemre
2426           izmir         cesme         alacati
386            izmir          buca       kurucesme
6584           mugla        bodrum        akcaalan
6167           mugla        bodrum        akyarlar
2572           izmir        dikili        salimbey
3877          manisa    sehzadeler   1_anafartalar
4154           aydin         didim      cumhuriyet
1328           izmir          buca  vali_rahmi_bey

In [37]:
print(df.columns)

Index(['list-view-price', 'celly', 'celly 2', 'celly 3', 'celly 4',
       'img-wrp href', 'city', 'district', 'neighborhood'],
      dtype='object')

In [38]:
print(df['celly'].unique())

['1 +\n                        1' '3 +\n                        1'
 '2 +\n                        1' '4 +\n                        1'
 '4 +\n                        2' '5 +\n                        1'
 '6 +\n                        1' '7 +\n                        1'
 '21 +\n                        1' '6 +\n                        2'
 '5 +\n                        2' 'Stüdyo'
 '7 +\n                        2' '3 +\n                        2'
 '2 +\n                        0' '6 +\n                        0'
 '9 +\n                        4' '9 +\n                        1'
 '3 +\n                        0' '1 +\n                        15'
 '2 +\n                        2' '8 +\n                        1'
 '41 +\n                        4' '4 +\n                        0'
 '1 +\n                        25' '4 +\n                        4'
 '3 +\n                        4' '1 +\n                        2'
 '3 +\n                        3' '31 +\n                        1'
 '4 +\n                        3' '9 +\n                        5'
 '8 +\n                        4' '4 +\n                        5'
 '9 +\n                        3' '25 +\n                        5'
 '8 +\n                        0' '9 +\n                        9'
 '14 +\n                        6' '10 +\n                        1']

In [39]:
df['celly']= df['celly'].apply(lambda x: x.replace('Stüdyo','1+0'))
df['celly']= df['celly'].apply(lambda x: x.replace('\n',''))
df['room']= df['celly'].apply(lambda x: x.split('+')[0]).astype(int)
df['living_room']= df['celly'].apply(lambda x: x.split('+')[1]).astype(int)

In [40]:
print(df['room'].unique())
print(df['living_room'].unique())

[ 1  3  2  4  5  6  7 21  9  8 41 31 25 14 10]
[ 1  2  0  4 15 25  3  5  9  6]

In [41]:
drop_columns(df, ['celly'])

In [42]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   celly 2          8136 non-null   object
 2   celly 3          8136 non-null   object
 3   celly 4          6858 non-null   object
 4   img-wrp href     4555 non-null   object
 5   city             8136 non-null   object
 6   district         8136 non-null   object
 7   neighborhood     8136 non-null   object
 8   room             8136 non-null   int64
 9   living_room      8136 non-null   int64
dtypes: int64(2), object(8)
memory usage: 635.8+ KB
None

In [43]:
print(df['celly 2'].unique())

['55 m²' '150 m²' '60 m²' '160 m²' '135 m²' '67 m²' '140 m²' '170 m²'
 '130 m²' '230 m²' '220 m²' '210 m²' '89 m²' '120 m²' '200 m²' '355 m²'
 '75 m²' '110 m²' '100 m²' '65 m²' '145 m²' '115 m²' '1.000 m²' '250 m²'
 '105 m²' '50 m²' '87 m²' '90 m²' '85 m²' '155 m²' '275 m²' '240 m²'
 '95 m²' '174 m²' '80 m²' '125 m²' '180 m²' '165 m²' '350 m²' '97 m²'
 '45 m²' '300 m²' '84 m²' '42 m²' '98 m²' '86 m²' '500 m²' '70 m²' '51 m²'
 '73 m²' '132 m²' '325 m²' '141 m²' '450 m²' '600 m²' '47 m²' '72 m²'
 '71 m²' '3.000 m²' '175 m²' '320 m²' '280 m²' '156 m²' '190 m²' '78 m²'
 '162 m²' '185 m²' '18 m²' '330 m²' '151 m²' '56 m²' '136 m²' '131 m²'
 '48 m²' '580 m²' '119 m²' '147 m²' '77 m²' '245 m²' '35 m²' '375 m²'
 '146 m²' '161 m²' '163 m²' '149 m²' '206 m²' '138 m²' '93 m²' '63 m²'
 '41 m²' '183 m²' '96 m²' '108 m²' '76 m²' '475 m²' '359 m²' '124 m²'
 '91 m²' '194 m²' '43 m²' '4.500 m²' '68 m²' '205 m²' '20 m²' '103 m²'
 '53 m²' '270 m²' '58 m²' '302 m²' '505 m²' '800 m²' '168 m²' '154 m²'
 '368 m²' '178 m²' '40 m²' '750 m²' '92 m²' '181 m²' '400 m²' '30 m²'
 '260 m²' '460 m²' '390 m²' '64 m²' '360 m²' '340 m²' '550 m²' '38 m²'
 '121 m²' '4.000 m²' '295 m²' '112 m²' '137 m²' '22 m²' '128 m²'
 '3.200 m²' '440 m²' '122 m²' '370 m²' '380 m²' '204 m²' '148 m²' '142 m²'
 '520 m²' '166 m²' '870 m²' '143 m²' '57 m²' '286 m²' '81 m²' '116 m²'
 '209 m²' '59 m²' '106 m²' '74 m²' '1.301 m²' '52 m²' '167 m²' '217 m²'
 '25 m²' '290 m²' '196 m²' '184 m²' '159 m²' '195 m²' '640 m²' '285 m²'
 '235 m²' '337 m²' '211 m²' '134 m²' '832 m²' '152 m²' '88 m²' '213 m²'
 '126 m²' '255 m²' '199 m²' '127 m²' '11 m²' '66 m²' '399 m²' '187 m²'
 '341 m²' '745 m²' '118 m²' '144 m²' '15 m²' '535 m²' '5.500 m²' '114 m²'
 '208 m²' '94 m²' '46 m²' '173 m²' '900 m²' '225 m²' '402 m²' '111 m²'
 '193 m²' '1.100 m²' '212 m²' '102 m²' '177 m²' '101 m²' '164 m²' '158 m²'
 '62 m²' '172 m²' '9.000 m²' '21 m²' '117 m²' '82 m²' '49 m²' '176 m²'
 '182 m²' '981 m²' '256 m²' '32 m²' '3.510 m²' '215 m²' '1.057 m²'
 '171 m²' '79 m²' '169 m²' '28 m²' '104 m²' '201 m²' '310 m²' '1.150 m²'
 '2.000 m²' '228 m²' '700 m²' '349 m²' '203 m²' '510 m²' '31 m²' '33 m²'
 '950 m²' '650 m²' '252 m²' '493 m²' '265 m²' '1.400 m²' '5 m²' '113 m²'
 '36 m²' '317 m²' '850 m²' '249 m²' '109 m²' '420 m²' '995 m²' '545 m²'
 '192 m²' '1.250 m²' '490 m²' '760 m²' '157 m²' '54 m²' '405 m²' '99 m²']

In [44]:
df['celly 2']= df['celly 2'].apply(lambda x: x.replace('.',''))

In [45]:
print(df['celly 2']. unique())

['55 m²' '150 m²' '60 m²' '160 m²' '135 m²' '67 m²' '140 m²' '170 m²'
 '130 m²' '230 m²' '220 m²' '210 m²' '89 m²' '120 m²' '200 m²' '355 m²'
 '75 m²' '110 m²' '100 m²' '65 m²' '145 m²' '115 m²' '1000 m²' '250 m²'
 '105 m²' '50 m²' '87 m²' '90 m²' '85 m²' '155 m²' '275 m²' '240 m²'
 '95 m²' '174 m²' '80 m²' '125 m²' '180 m²' '165 m²' '350 m²' '97 m²'
 '45 m²' '300 m²' '84 m²' '42 m²' '98 m²' '86 m²' '500 m²' '70 m²' '51 m²'
 '73 m²' '132 m²' '325 m²' '141 m²' '450 m²' '600 m²' '47 m²' '72 m²'
 '71 m²' '3000 m²' '175 m²' '320 m²' '280 m²' '156 m²' '190 m²' '78 m²'
 '162 m²' '185 m²' '18 m²' '330 m²' '151 m²' '56 m²' '136 m²' '131 m²'
 '48 m²' '580 m²' '119 m²' '147 m²' '77 m²' '245 m²' '35 m²' '375 m²'
 '146 m²' '161 m²' '163 m²' '149 m²' '206 m²' '138 m²' '93 m²' '63 m²'
 '41 m²' '183 m²' '96 m²' '108 m²' '76 m²' '475 m²' '359 m²' '124 m²'
 '91 m²' '194 m²' '43 m²' '4500 m²' '68 m²' '205 m²' '20 m²' '103 m²'
 '53 m²' '270 m²' '58 m²' '302 m²' '505 m²' '800 m²' '168 m²' '154 m²'
 '368 m²' '178 m²' '40 m²' '750 m²' '92 m²' '181 m²' '400 m²' '30 m²'
 '260 m²' '460 m²' '390 m²' '64 m²' '360 m²' '340 m²' '550 m²' '38 m²'
 '121 m²' '4000 m²' '295 m²' '112 m²' '137 m²' '22 m²' '128 m²' '3200 m²'
 '440 m²' '122 m²' '370 m²' '380 m²' '204 m²' '148 m²' '142 m²' '520 m²'
 '166 m²' '870 m²' '143 m²' '57 m²' '286 m²' '81 m²' '116 m²' '209 m²'
 '59 m²' '106 m²' '74 m²' '1301 m²' '52 m²' '167 m²' '217 m²' '25 m²'
 '290 m²' '196 m²' '184 m²' '159 m²' '195 m²' '640 m²' '285 m²' '235 m²'
 '337 m²' '211 m²' '134 m²' '832 m²' '152 m²' '88 m²' '213 m²' '126 m²'
 '255 m²' '199 m²' '127 m²' '11 m²' '66 m²' '399 m²' '187 m²' '341 m²'
 '745 m²' '118 m²' '144 m²' '15 m²' '535 m²' '5500 m²' '114 m²' '208 m²'
 '94 m²' '46 m²' '173 m²' '900 m²' '225 m²' '402 m²' '111 m²' '193 m²'
 '1100 m²' '212 m²' '102 m²' '177 m²' '101 m²' '164 m²' '158 m²' '62 m²'
 '172 m²' '9000 m²' '21 m²' '117 m²' '82 m²' '49 m²' '176 m²' '182 m²'
 '981 m²' '256 m²' '32 m²' '3510 m²' '215 m²' '1057 m²' '171 m²' '79 m²'
 '169 m²' '28 m²' '104 m²' '201 m²' '310 m²' '1150 m²' '2000 m²' '228 m²'
 '700 m²' '349 m²' '203 m²' '510 m²' '31 m²' '33 m²' '950 m²' '650 m²'
 '252 m²' '493 m²' '265 m²' '1400 m²' '5 m²' '113 m²' '36 m²' '317 m²'
 '850 m²' '249 m²' '109 m²' '420 m²' '995 m²' '545 m²' '192 m²' '1250 m²'
 '490 m²' '760 m²' '157 m²' '54 m²' '405 m²' '99 m²']

In [46]:
df['area']= df['celly 2'].apply(lambda x : x.split(' ')[0]).astype(int)
#hücreyi boşluk karakterinden böler 0. indisi alır. Split ayıraç görevi görür

In [47]:
print(df['area'].unique())

[  55  150   60  160  135   67  140  170  130  230  220  210   89  120
  200  355   75  110  100   65  145  115 1000  250  105   50   87   90
   85  155  275  240   95  174   80  125  180  165  350   97   45  300
   84   42   98   86  500   70   51   73  132  325  141  450  600   47
   72   71 3000  175  320  280  156  190   78  162  185   18  330  151
   56  136  131   48  580  119  147   77  245   35  375  146  161  163
  149  206  138   93   63   41  183   96  108   76  475  359  124   91
  194   43 4500   68  205   20  103   53  270   58  302  505  800  168
  154  368  178   40  750   92  181  400   30  260  460  390   64  360
  340  550   38  121 4000  295  112  137   22  128 3200  440  122  370
  380  204  148  142  520  166  870  143   57  286   81  116  209   59
  106   74 1301   52  167  217   25  290  196  184  159  195  640  285
  235  337  211  134  832  152   88  213  126  255  199  127   11   66
  399  187  341  745  118  144   15  535 5500  114  208   94   46  173
  900  225  402  111  193 1100  212  102  177  101  164  158   62  172
 9000   21  117   82   49  176  182  981  256   32 3510  215 1057  171
   79  169   28  104  201  310 1150 2000  228  700  349  203  510   31
   33  950  650  252  493  265 1400    5  113   36  317  850  249  109
  420  995  545  192 1250  490  760  157   54  405   99]

In [48]:
drop_columns(df, ['celly 2'])

In [49]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   celly 3          8136 non-null   object
 2   celly 4          6858 non-null   object
 3   img-wrp href     4555 non-null   object
 4   city             8136 non-null   object
 5   district         8136 non-null   object
 6   neighborhood     8136 non-null   object
 7   room             8136 non-null   int64
 8   living_room      8136 non-null   int64
 9   area             8136 non-null   int64
dtypes: int64(3), object(7)
memory usage: 635.8+ KB
None

In [50]:
print(df['celly 3'].unique())

['25\n                      Yaşında' '35\n                      Yaşında'
 '2\n                      Yaşında' '27\n                      Yaşında'
 '15\n                      Yaşında' '10\n                      Yaşında'
 '20\n                      Yaşında' '30\n                      Yaşında'
 '16\n                      Yaşında' '11\n                      Yaşında'
 '31\n                      Yaşında' 'Sıfır Bina'
 '5\n                      Yaşında' '26\n                      Yaşında'
 '12\n                      Yaşında' '4\n                      Yaşında'
 '6\n                      Yaşında' '22\n                      Yaşında'
 '23\n                      Yaşında' '29\n                      Yaşında'
 '3\n                      Yaşında' '8\n                      Yaşında'
 '33\n                      Yaşında' '50\n                      Yaşında'
 '7\n                      Yaşında' '18\n                      Yaşında'
 '32\n                      Yaşında' '28\n                      Yaşında'
 '14\n                      Yaşında' '40\n                      Yaşında'
 '9\n                      Yaşında' '21\n                      Yaşında'
 '45\n                      Yaşında' '38\n                      Yaşında'
 '19\n                      Yaşında' '24\n                      Yaşında'
 '17\n                      Yaşında' '1\n                      Yaşında'
 '36\n                      Yaşında' '34\n                      Yaşında'
 '13\n                      Yaşında' '42\n                      Yaşında'
 '44\n                      Yaşında' '43\n                      Yaşında'
 '37\n                      Yaşında' '55\n                      Yaşında'
 '47\n                      Yaşında' '39\n                      Yaşında'
 '49\n                      Yaşında' '52\n                      Yaşında'
 '300\n                      Yaşında' '199\n                      Yaşında'
 '48\n                      Yaşında' '60\n                      Yaşında'
 '61\n                      Yaşında' '600\n                      Yaşında'
 '100\n                      Yaşında']

In [51]:
df['celly 3'] = df['celly 3'].apply(lambda x : x.replace('Sıfır Bina','0 yaşında'))
df['celly 3'] = df['celly 3'].apply(lambda x : x.replace('\n',' '))
df['age'] =df['celly 3'].apply(lambda x: x.split(' ')[0]).astype(int)

In [52]:
print(df['age'].unique())

[ 25  35   2  27  15  10  20  30  16  11  31   0   5  26  12   4   6  22
  23  29   3   8  33  50   7  18  32  28  14  40   9  21  45  38  19  24
  17   1  36  34  13  42  44  43  37  55  47  39  49  52 300 199  48  60
  61 600 100]

In [53]:
print(df['celly 3'].unique())

['25                       Yaşında' '35                       Yaşında'
 '2                       Yaşında' '27                       Yaşında'
 '15                       Yaşında' '10                       Yaşında'
 '20                       Yaşında' '30                       Yaşında'
 '16                       Yaşında' '11                       Yaşında'
 '31                       Yaşında' '0 yaşında'
 '5                       Yaşında' '26                       Yaşında'
 '12                       Yaşında' '4                       Yaşında'
 '6                       Yaşında' '22                       Yaşında'
 '23                       Yaşında' '29                       Yaşında'
 '3                       Yaşında' '8                       Yaşında'
 '33                       Yaşında' '50                       Yaşında'
 '7                       Yaşında' '18                       Yaşında'
 '32                       Yaşında' '28                       Yaşında'
 '14                       Yaşında' '40                       Yaşında'
 '9                       Yaşında' '21                       Yaşında'
 '45                       Yaşında' '38                       Yaşında'
 '19                       Yaşında' '24                       Yaşında'
 '17                       Yaşında' '1                       Yaşında'
 '36                       Yaşında' '34                       Yaşında'
 '13                       Yaşında' '42                       Yaşında'
 '44                       Yaşında' '43                       Yaşında'
 '37                       Yaşında' '55                       Yaşında'
 '47                       Yaşında' '39                       Yaşında'
 '49                       Yaşında' '52                       Yaşında'
 '300                       Yaşında' '199                       Yaşında'
 '48                       Yaşında' '60                       Yaşında'
 '61                       Yaşında' '600                       Yaşında'
 '100                       Yaşında']

In [54]:
drop_columns(df, ['celly 3']) #celly 3 kolonundan kurtuluyoruz

In [55]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   celly 4          6858 non-null   object
 2   img-wrp href     4555 non-null   object
 3   city             8136 non-null   object
 4   district         8136 non-null   object
 5   neighborhood     8136 non-null   object
 6   room             8136 non-null   int64
 7   living_room      8136 non-null   int64
 8   area             8136 non-null   int64
 9   age              8136 non-null   int64
dtypes: int64(4), object(6)
memory usage: 635.8+ KB
None

In [56]:
print(df['celly 4'].unique())

['Yüksek Giriş' '3. Kat' 'Ara Kat' '4. Kat' '2. Kat' 'Zemin' nan
 'Tripleks' 'Villa Katı' 'Bahçe Katı' '1. Kat' '8. Kat' '6. Kat'
 'Giriş Katı' '5. Kat' '7. Kat' '21 ve üzeri' 'En Üst Kat' 'Teras Katı'
 '13. Kat' 'Kot 1' '9. Kat' 'Çatı Katı' '10. Kat' '12. Kat' 'Kot 2'
 '15. Kat' 'Bodrum ve Zemin' '11. Kat' 'Kot 3' '18. Kat' '20. Kat'
 'Yarı Bodrum' '14. Kat' '16. Kat' '17. Kat' 'Asma Kat' 'Bodrum' '19. Kat']

In [57]:
search_for = [
    'Kot 2',
      'Kot 1'
      ]
replace_with = [
    '-2.Kat',
      '-1.Kat'
      ]
replace_dict ={
    'Kot 2': '-2.Kat',
    'Kot 1': '-1.Kat',
    'Yüksek Giriş': '1.Kat',
    'Ara Kat': '3.Kat',
    'En Üst Kat': '5.Kat',
    'Bahçe Katı': '0.Kat',
    'Yarı Bodrum':'0.Kat',
    'Bodrum':'0.Kat',
    'Kot 3': '-3.Kat',
    'Çatı Katı': '5.kat',
    'Zemin':'0.Kat',
    'Giriş Katı':'0.Kat',
    'Villa Katı':'0.Kat',
    '21 ve üzeri':'21.Kat',
    'Bodrum ve Zemin': '0.Kat',
    'Asma Kat':'1.Kat',
    'Tripleks': '0.Kat',
    'Teras Katı':'5.Kat',
    'nan':'2.Kat'
}
df['celly 4']= df['celly 4'].replace(replace_dict.keys(),replace_dict.values()).astype(str)
df['celly 4'].dropna(inplace=True)
df['floor']= df['celly 4'].apply(lambda x: x.split('.')[0]).astype(int)

ValueError: invalid literal for int() with base 10: 'nan'

In [ ]:
print(df['floor'].unique())

[ 1  3  4  2  0  8  6  5  7 21 13 -1  9 10 12 -2 15 11 -3 18 20 14 16 17
 19]

In [ ]:
drop_columns(df,['celly 4'])

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   img-wrp href     4555 non-null   object
 2   city             8136 non-null   object
 3   district         8136 non-null   object
 4   neighborhood     8136 non-null   object
 5   room             8136 non-null   int64
 6   living_room      8136 non-null   int64
 7   area             8136 non-null   int64
 8   age              8136 non-null   int64
 9   floor            8136 non-null   int64
dtypes: int64(5), object(5)
memory usage: 635.8+ KB
None

In [ ]:
print(df['list-view-price'].unique())

['12.000' '16.000' '200' '18.000' '45.000' '35.000' '25.000' '22.000'
 '15.000' '24.000' '240.000' '1.200.000' '30.000' '20.000' '180.000'
 '60.000' '10.500' '10.000' '55.000' '13.000' '12.500' '21.000' '250.000'
 '190.000' '42.500' '17.000' '11.000' '450.000' '27.500' '80.000' '23.000'
 '550.000' '19.750' '75.000' '50.000' '34.000' '19.500' '28.500' '24.500'
 '325.000' '28.000' '29.000' '750.000' '600.000' '16.750' '500.000'
 '14.000' '220.000' '19.000' '21.500' '350.000' '9.000' '14.500' '25.500'
 '18.500' '300.000' '480.000' '150.000' '5.000' '16.500' '525.000'
 '370.000' '13.750' '17.500' '27.000' '11.500' '200.000' '90.000' '64.000'
 '15.750' '118.000' '1.000.000' '400.000' '70.000' '13.500' '210.000'
 '38.000' '1.800.000' '31.500' '57.500' '49.900' '2.000' '4.875.000'
 '8.500' '700.000' '15.250' '7.000' '40.000' '18.750' '22.500' '1.250.000'
 '3.500' '32.000' '104.000' '1.600.000' '120.000' '20.500' '650.000'
 '65.000' '48.000' '850.000' '17.250' '48.500' '100.000' '22.500.000'
 '115.000' '57.000' '53.000' '66.000' '12.950' '62.000' '265.000' '18.250'
 '185.000' '41.000' '110.000' '26.900' '17.750' '62.500' '130.000' '7.500'
 '33.000' '29.999' '14.750' '37.000' '16.200' '275.000' '26.000' '8.000'
 '375.000' '8.250' '39.500' '98.500' '46.000' '28.900' '9.250' '58.000'
 '15.900' '10.757' '85.000' '10.750' '1.400.000' '175.000' '460.000'
 '29.500' '13.250' '20.999' '31.000' '9.500' '15.500' '56.000' '14.700'
 '269.900' '14.100' '530.000' '16.250' '49.000' '36.500' '225.000' '6.500'
 '17.950' '10.900' '8.750' '620.000' '140.000' '9.750' '125.000' '24.750'
 '2.550.000' '1.000' '6.000' '95.000' '37.500' '7.250' '43.000' '5.500'
 '83.000' '380.000' '280.000' '350' '4.500' '800.000' '39.000' '21.750'
 '235.000' '96.000' '1.100.000' '425.000' '52.500' '19.360' '4.000'
 '9.800' '680.000' '15.590.000' '34.500' '170.000' '26.500' '18.450'
 '1.650.000' '23.500' '365.000' '36.000' '10.400' '10.999' '160.000'
 '7.950' '785.000' '2.250.000' '260.000' '13.900.000' '165.000' '2.500'
 '290.000' '300' '475.000' '9.999' '9.200' '330.000' '2.265.000' '590.000'
 '23' '29.750' '14.250' '1.050.000' '1.750.000' '415.000' '430.000'
 '11.111' '720.000' '625.000' '1.350.000' '15.950' '14.999' '195.000'
 '8.000.000' '1.025.000' '67.000' '900.000' '1.500' '14.990' '950.000'
 '270.000' '3.000' '10.800' '13.950' '780.000' '320.000' '1.250' '63.000'
 '1.200' '675.000' '8.950' '760.000' '420.000' '13' '67.500' '12' '26.750'
 '4.950' '440.000' '15' '390.000' '1.725.000' '7.800' '7.750' '12.750'
 '16.500.000' '11.250' '7.900' '12.850' '11.750' 7.5 4.5 10.0 8.0 19.0 6.5
 18.5 9.5 7.0 12.0 6.0 8.5 15.0 9.0 7.75 6.75 16.5 20.0 22.0 7.25 21.0
 14.0 '4.250' '5.250' '6.750' '6.600' '5.100' '5.600' '9.850' '26.000.000'
 '3.400' '14.300' '8.700' '9.950.000' '120.000.000' '111' '11' '890.000'
 '42.000' '4.650.000' '1.700' '8.550' '8.900' '7.200' '3.500.000' '11.900'
 '1.190.000' '1.840.000' '6.250' '8.100' '750' '7.999' '3.999' '6.900'
 '5.750' '7.400' '6.999' '1.850.000' '7.100' '6.800' '5.700' '9.900'
 '4.999' '4.750' '5.999' '8.400' '8.300' '44.000' '740.000' '2.500.000'
 '360.000' '105.000' '355.000' '255.000' '72.000' '1' '485.000' '285.000'
 '59.500' '245.000' '4.050.000' '135.000' '32.500' '510.000' '1.225.000'
 '3.900.000' '3.250' '30.000.000' '39.900' '243.000' '2.300.000'
 '25.000.000' '49.950' '73.000' '840.000' '2.275.000' '410.000' '310.000'
 '7.300' '32.750' '3.750' '3.000.000' '1.700.000' '1.150.000' '2.750'
 '4.100' '16.350' '17.000.000' '921.180' '145.000' '41.600' '495.000'
 '65.500' '2.250' '595.000' '19.800' '54.000' '50.000.000' '48.000.000'
 '465.000' '860.000' '630.000' '995.000' '241.800' '340.000' '4.450.000'
 '6.500.000' '2.175.000' '2.000.000' '2.200.000' '6.150.000' '16.400'
 '295.000' '1.070.000' '87.000' '1.750' '875.000' '560.000' '3.250.000'
 '790.000']

In [ ]:
df['list-view-price']= df['list-view-price'].astype(str).apply(lambda x: x.replace('.',''))
df['price']= df['list-view-price'].astype(int)

In [ ]:
print(df['price'].unique())

[    12000     16000       200     18000     45000     35000     25000
     22000     15000     24000    240000   1200000     30000     20000
    180000     60000     10500     10000     55000     13000     12500
     21000    250000    190000     42500     17000     11000    450000
     27500     80000     23000    550000     19750     75000     50000
     34000     19500     28500     24500    325000     28000     29000
    750000    600000     16750    500000     14000    220000     19000
     21500    350000      9000     14500     25500     18500    300000
    480000    150000      5000     16500    525000    370000     13750
     17500     27000     11500    200000     90000     64000     15750
    118000   1000000    400000     70000     13500    210000     38000
   1800000     31500     57500     49900      2000   4875000      8500
    700000     15250      7000     40000     18750     22500   1250000
      3500     32000    104000   1600000    120000     20500    650000
     65000     48000    850000     17250     48500    100000  22500000
    115000     57000     53000     66000     12950     62000    265000
     18250    185000     41000    110000     26900     17750     62500
    130000      7500     33000     29999     14750     37000     16200
    275000     26000      8000    375000      8250     39500     98500
     46000     28900      9250     58000     15900     10757     85000
     10750   1400000    175000    460000     29500     13250     20999
     31000      9500     15500     56000     14700    269900     14100
    530000     16250     49000     36500    225000      6500     17950
     10900      8750    620000    140000      9750    125000     24750
   2550000      1000      6000     95000     37500      7250     43000
      5500     83000    380000    280000       350      4500    800000
     39000     21750    235000     96000   1100000    425000     52500
     19360      4000      9800    680000  15590000     34500    170000
     26500     18450   1650000     23500    365000     36000     10400
     10999    160000      7950    785000   2250000    260000  13900000
    165000      2500    290000       300    475000      9999      9200
    330000   2265000    590000        23     29750     14250   1050000
   1750000    415000    430000     11111    720000    625000   1350000
     15950     14999    195000   8000000   1025000     67000    900000
      1500     14990    950000    270000      3000     10800     13950
    780000    320000      1250     63000      1200    675000      8950
    760000    420000        13     67500        12     26750      4950
    440000        15    390000   1725000      7800      7750     12750
  16500000     11250      7900     12850     11750        75        45
       100        80       190        65       185        95        70
       120        60        85       150        90       775       675
       165       220       725       210       140      4250      5250
      6750      6600      5100      5600      9850  26000000      3400
     14300      8700   9950000 120000000       111        11    890000
     42000   4650000      1700      8550      8900      7200   3500000
     11900   1190000   1840000      6250      8100       750      7999
      3999      6900      5750      7400      6999   1850000      7100
      6800      5700      9900      4999      4750      5999      8400
      8300     44000    740000   2500000    360000    105000    355000
    255000     72000         1    485000    285000     59500    245000
   4050000    135000     32500    510000   1225000   3900000      3250
  30000000     39900    243000   2300000  25000000     49950     73000
    840000   2275000    410000    310000      7300     32750      3750
   3000000   1700000   1150000      2750      4100     16350  17000000
    921180    145000     41600    495000     65500      2250    595000
     19800     54000  50000000  48000000    465000    860000    630000
    995000    241800    340000   4450000   6500000   2175000   2000000
   2200000   6150000     16400    295000   1070000     87000      1750
    875000    560000   3250000    790000]

In [ ]:
drop_columns(df,['list-view-price'])

In [ ]:
print(df.columns)

Index(['img-wrp href', 'city', 'district', 'neighborhood', 'room',
       'living_room', 'area', 'age', 'floor', 'price'],
      dtype='object')

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img-wrp href  4555 non-null   object
 1   city          8136 non-null   object
 2   district      8136 non-null   object
 3   neighborhood  8136 non-null   object
 4   room          8136 non-null   int64
 5   living_room   8136 non-null   int64
 6   area          8136 non-null   int64
 7   age           8136 non-null   int64
 8   floor         8136 non-null   int64
 9   price         8136 non-null   int64
dtypes: int64(6), object(4)
memory usage: 635.8+ KB
None

In [ ]:
drop_columns(df,['img-wrp href'])

In [59]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   celly 4          8136 non-null   object
 2   img-wrp href     4555 non-null   object
 3   city             8136 non-null   object
 4   district         8136 non-null   object
 5   neighborhood     8136 non-null   object
 6   room             8136 non-null   int64
 7   living_room      8136 non-null   int64
 8   area             8136 non-null   int64
 9   age              8136 non-null   int64
dtypes: int64(4), object(6)
memory usage: 635.8+ KB
None

In [ ]:
df.to_csv('data.csv',index=False)